#!/bin/python
import os
import base64
import inginious.feedback

text = os.popen('getinput myname').read().strip('\n')

#command = 'convert smiley.jpg -fill blue '+\
#          '-font CANDY.TTF -pointsize 72 label:"Hello '+text+'" '+\
#          '-append new.jpg'

#os.popen(command).read()

os.system("rst-image new.jpg | feedback-msg -a")
inginious.feedback.set_global_result("success")