#! /bin/bash

getinput dictee > userinput.txt

original=`cat solution.txt`
userinput=`cat userinput.txt`
retval=`wdiff userinput.txt solution.txt`

if [ "$original" = "$retval" ]; then
	feedback --result success --feedback "Bravo!"
else
    feedback --result failed --feedback "$retval"
fi